load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar")
load("@pip_recipe_book//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "index_generator",
    srcs = [
        "__init__.py",
        "index_generator.py",
    ],
    data = [":index.html.jinja2"],
    deps = [
        requirement("absl-py"),
        requirement("jinja2"),
    ],
)

genrule(
    name = "index",
    srcs = [
        "//:recipe_manifests",
        "//:book",
        "//:book.tex",
    ],
    outs = ["index.html"],
    cmd = "./$(location //website:index_generator) $(locations //:recipe_manifests) $(location //:book) $(location //:book.tex) > $@",
    stamp = 1,
    tools = ["//website:index_generator"],
    visibility = ["//visibility:public"],
)

pkg_tar(
    name = "website",
    srcs = [
        ":index",
        "//:book",
        "//:single_pages",
        "//:recipe_pages",
    ],
    visibility = ["//visibility:public"],
)

# `bazel run //website:preview` to browse the site locally.
py_binary(
    name = "preview",
    srcs = [
        "__init__.py",
        "preview.py",
    ],
    data = [":website"],
    deps = [
        requirement("absl-py"),
    ],
)
